name: Kimi-Dev Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HF_HUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Run Kimi-Dev on all Python files
        run: |
          find . -name '*.py' -not -path './.github/*' | while read file; do
            echo "🛠️ Reviewing $file"
            python run_kimi.py "$file"
            echo
          done
