
permissions:
  contents: read
  issues: write

name: Kimi-Dev Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HF_HUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Run Kimi-Dev on all Python files
        run: |
          mkdir -p $RUNNER_TEMP/_github_workflow
          find . -name '*.py' -not -path './.github/*' | while read file; do
            echo "🛠️ Reviewing $file"
            python run_kimi.py "$file"
            echo
          done | tee $RUNNER_TEMP/_github_workflow/kimi_review.log

      - name: Post report as PR comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reportPath = process.env.RUNNER_TEMP + '/_github_workflow/kimi_review.log';
            const report = fs.readFileSync(reportPath, 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "🛠️ **Kimi-Dev Suggests:**\n\n```\n" + report + "\n```"
            });
