# .github/workflows/kimi_review.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

name: Kimi-Dev Code Review

on:
  pull_request_target:
    branches: [main]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Hugging Face Login
        run: huggingface-cli login --token "${{ secrets.HUGGINGFACEHUB_API_TOKEN }}"

      - name: Run Kimi-Dev review on Python files
        run: |
          find . -name '*.py' -not -path './.github/*' | while read file; do
            echo "🔍 Reviewing $file"
            python run_kimi.py "$file"
          done
