# .github/workflows/kimi_review.yml

permissions:
  contents: read        # allow reading your repo
  issues: write         # allow posting PR comments

name: Kimi-Dev Code Review

on:
  pull_request_target:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Log in to Hugging Face
        run: huggingface-cli login --token "${{ secrets.HF_HUB_TOKEN }}"

      - name: Run Kimi-Dev on all Python files
        run: |
          find . -name '*.py' -not -path './.github/*' | while read file; do
            echo "🔍 Reviewing $file"
            python run_kimi.py "$file"
          done
